### ISSUE TITLE
Publish Unit test results Azure DevOps

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#16]
## Overview

<https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops>

## Tasks

- [x] Generate and publish coverage report

  - <https://stackoverflow.com/questions/24825860/code-coverage-for-jest>
  - <https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops#publish-code-coverage-results>

- [x] Integrate jest-junit
  - <https://www.npmjs.com/package/jest-junit>

- [x] Publish test results
  - <https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops#publish-test-results>

- [x] Update validation script for test publishing
