### ISSUE TITLE
Feature: Assertion Function

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#20]
https://en.wikipedia.org/wiki/Assertion_(software_development)

## Requirements

- [x] The assertion function must be documented. #1
- [x] The assertion function must support assertion signatures from TypeScript 3.7+. #21
- [x] ~~Assertions must be toggleable. #8~~
- [x] Assertions must support throwing custom error types. #22
- [x] ~~Assertions must return a boolean in all modes. #23~~
