### ISSUE TITLE
Feature: invariant

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#26]
- [x] The 'invariant' declaration must be documented. #27 
- [x] ~The invariant decorator must be class decorator only. #28~
- [x] ~There can be multiple invariant decorators assigned to a class. #29~
- [x] The subclasses of a contracted class must obey the invariants #30
- [x] A truthy invariant does not throw an exception when evaluated. #31
- [x] A falsy invariant throws an exception when evaluated. #32
- [x] An invariant is evaluated after it's associated class is constructed. #33
- [x] An invariant is evaluated before and after every method call on the associated class. #34
- [x] Public properties must be forbidden. #35
- [x] ~A class feature with a decorator must not be functional until the @invariant is defined. #36~
- [x] ~The invariant decorator has a checked mode and unchecked mode. #37~
- [x] In checked mode the invariant is evaluated #38
- [x] In unchecked mode the invariant is not evaluated. #39
- [x] A subclass with its own invariants must enforce all ancestor invariants. #40
- [x] ~@invariant supports use with no arguments. #41~
- [x] ~There can be multiple invariants assigned to a contract #178~
