### ISSUE TITLE
Feature: override

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#42]
## References
- <https://www.tutorialspoint.com/java/java_overriding.htm>

## Requirements

- [x] The 'override' decorator must be documented. #43 
- [x] A subclass with an overriding member missing @override is an error. #48
- [x] Accessors must support @override. #50
- [ ] Contravariance of method arguments in the subtype. #51
- [x] ~~In production mode the @override decorator is a no-op. #45~~
- [x] Only a single @override can be assigned to a member per class. #54
- [x] ~~The 'override' decorator must not be functional until the invariant decorator is defined. #53~~
- [x] The 'override' decorator must have a Contracted class in it's ancestry #170
- [x] The override decorator is a non-static member decorator only. #44
- [ ] The parameter names and positions of an overridden method must match its ancestor's. #52
- [ ] TypeScript support? #49
- [x] Using @override on a class member with no ancestor member is an error. #46
- [x] Using @override on a method with an ancestor with a different parameter count is an error. #47
