### ISSUE TITLE
Feature: rescue

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#67]
- [x] The 'rescue' decorator must be documented. #55 
- [x] ~~An error thrown by a member must be a subtype of an error thrown by its supertype method.~~ #56
- [x] ~~The @rescue decorator is a class and non-static class feature decorator excluding properties.~~ #57
- [x] The `rescue` declaration must preserve the invariant after execution #58
- [x] Any error thrown by a class feature must be captured by its @rescue #59
- [x] The `rescue` declarations are enabled in checkedMode and disabled otherwise #60
- [x] ~~Only a single `rescue` can be declared per feature~~ #61
- [x] The `retry` argument of the `rescue` declaration can only be called once during rescue execution #62
- [x] If a `rescue` is executed and the `retry` argument is not called then the original error is thrown #63
- [x] If an exception is thrown in a class feature without a `rescue` defined then the exception is raised to its caller after the `invariant` is checked #64
- [x] If an error is thrown in `demands` the error is raised to the caller #65
- [x] If an error is raised in a `ensures` then the associated `rescue` is executed #66
