### ISSUE TITLE
Migrate from Azure to Github

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#7]
There is more public familiarity with GitHub than Azure, plus there is more simplicity currently. Now that Microsoft owns GitHub there is less of a desire to remain in the old location in order to leverage to benefits.

## Tasks
- [x] Migrate code
- [x] Migrate issues
- [x] Configure CI (#103, #104, #124)
- [x] Configure CD (#124)
- [x] Delete Azure DevOps repo
- [x] Replace local repos with this one
- [x] Change @thenewobjective namespace to @final-hill (#102)
