### ISSUE TITLE
Feature: demands

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#72]
- [x] The `demands` assertion must be documented. #68
- [x] ~~The `@demands` decorator must be a non-static feature decorator only. #69~~
- [x] Demands assertions can be defined for a class feature. #70
- [x] Overridden features are still subject to the demands assertion. #71
- [x] The `demands` assertion is evaluated before its associated feature is called #73
- [x] `demands` assertions are enabled in `checkedMode` and disabled otherwise #74
- [x] `demands` assertions cannot be strengthened in a subtype #75
