### ISSUE TITLE
Feature: ensures

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#83]
- [x] The 'ensures' decorator must be documented #76
- [x] ~~The @ensures decorator must be a non-static method decorator only #77~~
- [x] Ensures assertions can be defined for a class feature. #78
- [x] Overridden features are still subject to the ensures assertion #79
- [x] The ensures assertion is evaluated after its associated feature is called #80
- [x] `ensures` assertions are enabled in checkedMode and disabled otherwise #81
- [x] Postconditions cannot be weakened in a subtype #82
- [x] `ensures` has access to the properties of the instance class before its associated member was executed #98
