### ISSUE TITLE
Feature: Contributing

### ISSUE THREAD

**Issue by mlhaufe** [final-hill/decorator-contracts#89]
- [ ] Contributors must sign a Contributor License Agreement (CLA). #86 
- [ ] CLAs must be stored. #87
- [ ] Contribution documentation and rules exist in CONTRIBUTING.md #88 #127

**Comment by mlhaufe** [comment]
I've decided to not accept contributions at this time. Just bug reports and feature requests
